### ISSUE TITLE
Needs to update to Node 20

### ISSUE THREAD

**Issue by maxnag** [euberdeveloper/ga-project-version#5]
Today I got this from the Gith:

Docker / build
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: **euberdeveloper/ga-project-version@main**. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by euberdeveloper** [comment]
It will be fixed in the next two days

**Comment by euberdeveloper** [comment]
Fixed from v3.0.0
